### ISSUE TITLE
False Positive Virustotal

### ISSUE THREAD

**Issue by FiftyFour7250** [andrewgosselin/music-recognition#1]
It was a great app, although I don't think anyone else used it except the us two. Now when I try to recognize, it says "Something went wrong, please check your audio settings", I reinstalled it, and even thought to start doing something with drivers, but then I noticed that song is recorded properly in the Temp folder, so this is not a device problem...

I hope it's possible to fix it, cause I didn't find anything similar to your app. I mean with record by sound, not mic.

(Also I hope you have enabled email notifications for this repositories :D)

![image](https://user-images.githubusercontent.com/78786088/120085390-6b47b180-c0e0-11eb-8515-07cfbb7b01a6.png)

**Comment by andrewgosselin** [comment]
I haven't updated this in a while but I actually do use it frequently.
Thanks for using the app, I have had plans to do an overhaul of it soon.

As for the error, I just made a dev build with a few fixes but I am not entirely sure as to what could be causing your issue so it may or may not fix it. I also added some logging, so if the dev build I attached to this reply doesn't fix your issue just attach the log file in `Program Files (x86) / Andrew Gosselin / MusicRecognizer /` in a reply and I will be sure to look into it.

To install the dev build just download the zip file below, delete all of the files in `Program Files (x86) / Andrew Gosselin / MusicRecognizer /` and unzip all of the files from the zip file into the folder.

[DevWithLogging.zip](https://github.com/andrewgosselin/music-recognition/files/6565511/DevWithLogging.zip)

**Comment by FiftyFour7250** [comment]
Yes! It fixed!
Thanks))


And while I'll continue to use it, but to be honest, it's a little disturbing.
https://www.virustotal.com/gui/file/b8a8cfd3c42583f6d31d1ac9e565c052b2e6e8dc007261de9d9860c45b3f50d9/detection

**Comment by andrewgosselin** [comment]
Awesome, glad to hear its fixed.

I believe that is a pretty common false positive with some applications that are zipped, as far some quick research suggests.
As I am not completely sure why that would be happening, I found a few github issues related to it which I have listed below.
https://www.reddit.com/r/antivirus/comments/hjajnb/have_infected_rar_but_need_to_install/
https://github.com/lian/msfs2020-go/issues/14
https://www.reddit.com/r/antivirus/comments/hjajnb/have_infected_rar_but_need_to_install/


I believe this will never happen in a release build since its packaged in a different way.
Sorry for the scare, thanks for bringing it to my attention, I will add this to my list of things to fix even if its just in dev builds.
I am actually going to rename this issue to `False Positive Virustotal` so I remember to look into this when I get the chance.

**Comment by FiftyFour7250** [comment]
Hey. It broke again. Even 5 days ago, it worked perfectly... Reinstalling (with dev build) didn't help. I don't know if this is related, but a couple days ago Nvidia Geforce updated my audio driver...

![image](https://user-images.githubusercontent.com/78786088/121792744-551e1300-cc01-11eb-9f67-372492478620.png)
[log.txt](https://github.com/andrewgosselin/music-recognition/files/6643141/log.txt)

**Comment by andrewgosselin-nt** [comment]
That may be it, they change around a lot of things when it comes to audio processing, I'll be sure to take a look at it when I get home from work.
I should have a v2 of this program ready next week hopefully, which I believe solves this issue but for now, I'll do a patch release, I'll make the release later today with the fixes and an installer rather than a dev build.

I'll link it here when I do it so you know.

**Comment by FiftyFour7250** [comment]
OK, thanks, and I attached the log above. I guess there is some kind of error with api...

**Comment by andrewgosselin** [comment]
https://github.com/andrewgosselin/music-recognition/releases/tag/1.0.2

I just made this release, I made a few changes to make versioning work for v2 as well, Before you install it be sure to purge any previous versions of the program, by both going to `ADD/REMOVE PROGRAMS` and also removing `../Program Files (x86)\Andrew Gosselin\Music Recognizer`.

**Comment by andrewgosselin** [comment]
@FiftyFour7250 Also on an unrelated note, do you think a hotkey would be a nice feature to have in V2? I thought about this but I was not sure if this would be used or not, I know personally I wouldn't really find much use for it but a couple of other people I know that use this have mentioned wanting a hotkey for recognizing the music.

**Comment by FiftyFour7250** [comment]
@andrewgosselin, Yea, it fixed. Thanks.

Regarding hotkeys - I do not know, personally I do not need it. I use the application 1-2 times a week, and it is not difficult for me to launch it through a shortcut on the desktop, or by double-clicking in the taskbar. And besides, hot keys will create a lot of problems, because for sure this combination can be used in some game, application, or somewhere else.

If you're thinking about new features, you'd better make a convenient redirect to Spotify. Because right now, the fastest way to play a song in Spotify is manually copy "spotify: track:..." to paste into the browser, and then it opens track in the Spotify app. It would be more convenient if when you click on the Windows notification about the found song, you would immediately open Spotify (or if this is not possible, then "spotify: track:..." in the browser, and then it redirects to the app). Of course, it''s not difficult to do this twice a week, but nevertheless))

**Comment by FiftyFour7250** [comment]
Hey. It broke again...

**Comment by andrewgosselin** [comment]
Looks like somehow the API key that was being used for that go invalidated.
Just re-enabled it, tested on my end and it seems to work.
Sorry for the late response, I haven't actually gotten a chance to work on much lately and also haven't been working on this application much so I hadnt noticed.

**Comment by andrewgosselin** [comment]
This project is being moved for a V2 build with a setting for the https://audd.io API key so it doesn't rely on me to keep up the subscription. Closing this issue since the newer version is built with a better framework than DotNet.
